### ISSUE TITLE
Add option to fetch the available QPUs from a database

### ISSUE THREAD

**Issue by HGSilveri** [pasqal-io/pasqal-cloud#37]
Needs to wait until Pulser supports device serialization/deserialization.

**Comment by bejito** [comment]
We could use some unique IDs to identify the devices both in pulser and in the backend, but then Pulser also needs the device specs in order to do local validation right ?

**Comment by HGSilveri** [comment]
Although it would possible to create abstract pulser sequences, the device is such a central part of a sequence that it would involve substantial changes to the sequence creation process. Furthermore, it would be likely that the sequence would then either fail validation or be adjusted to have unexpected consequences.
What is your concern with giving the device configuration to the user?
