### ISSUE TITLE
Add a more comprehensive name for the package

### ISSUE THREAD

**Issue by CdeTerra** [pasqal-io/pasqal-cloud#52]
Currently, the name to use to import the package is "sdk". This may lead to confusion to know what SDK it is about, and also potentially to collisions if other packages choose the same name. Would you consider to give a more explicit name, like "pasqal_cloud_sdk"?

**Comment by MatthieuMoreau0** [comment]
Thanks Clement, that's indeed something we want to change. This is in our backlog and should be addressed before public release.

**Comment by lvignoli** [comment]
Now the package name is `pasqal-sdk`, while the URL is `github.com/pasqal-io/cloud-sdk`.
This is also not ideal…

**Comment by MatthieuMoreau0** [comment]
Hello @CdeTerra, the github repo and package name on PyPi have been renamed as `pasqal-cloud`. 

You can also import our objects using `pasqal_cloud` e.g. `from pasqal_cloud import SDK`.

Closing this issue, let me know if you have questions!
