### ISSUE TITLE
If fetch_results=True in sdk.get_batch() we should wait for job completion 

### ISSUE THREAD

**Issue by awennersteen** [pasqal-io/pasqal-cloud#66]
This would make the behavior consistent with the job submission fetch_results behaviour.

**Comment by MatthieuMoreau0** [comment]
Is this not the case ? That sounds like a bug

**Comment by awennersteen** [comment]
I would say no (but I've not ran and confirmed yet)

As you see in the code (client), there is no check that the batch is done
```
    def _get_batch(
        self, id: str, fetch_results: bool = False
    ) -> Tuple[Dict[str, Any], List[Dict[str, Any]]]:
        batch_data: Dict[str, Any] = self._request(
            "GET", f"{self.endpoints.core}/api/v1/batches/{id}"
        )["data"]
        jobs_data = batch_data.pop("jobs", [])
        if fetch_results:
            results = self._request(
                "GET", f"{self.endpoints.core}/api/v1/batches/{id}/results"
            )["data"]
            for job_data in jobs_data:
                job_data["result"] = results.get(str(job_data["id"]), None)
        return batch_data, jobs_data
```

**Comment by MatthieuMoreau0** [comment]
Ah yes you're right I was thinking of the _create_batch function! Would be nice! I think we could just move all the logic that is inside the `create_batch` function to the `get_batch` function

Do you need this for QD module 2 release  ?

**Comment by awennersteen** [comment]
For now I just left this in a different library (because I wanted to do some other checks too, so it was nice), but as soon as this is released this would be something to fix. But we should probably take the time to consider all the functions and make sure that everything works as expected / desired.

**Comment by ArnaudPel** [comment]
Would also be convenient to support an optional `timeout` argument, for example in test environments where we know that the batch is supposed to take a few seconds at most.

Infinite waiting is a rather annoying experience when running a test suite.

**Comment by awennersteen** [comment]
deprecated fetch_results
